{ config, pkgs, ... }:

{
  imports = [
    # ? - Default hardware configurations generated by NixOS installer
    ./hardware-configuration.nix
    # ? - Additional hardware customizations (e.g., GPU, CPU tweaks)
    ./hardware.nix
    # ? - Bootloader and boot-related configurations
    ./boot.nix

    # ? - System-wide environment variables and packages
    ./environment.nix
    # ? - Custom Program Configurations
    ./programs.nix
    # ? - Fonts configuration
    ./fonts.nix
    # ? - System services configuration (audio, networking, printing, etc.)
    ./services.nix
    # ? - Timezone and locale settings
    ./time-zone.nix
    # ? - User accounts and permissions
    ./users.nix

    # ? - Networking configuration (NetworkManager, DNS, etc.)
    ./networking.nix
    # ? - Security configurations (firewall, polkit, etc.)
    ./security.nix
  ];

  # ? - Nixpkgs configuration
  # * - "https://search.nixos.org/options?channel=25.11&show=nixpkgs"
  nixpkgs = {
    # * - "https://search.nixos.org/options?channel=25.11&show=nixpkgs.config"
    config = {
      # ? - Allow installation of unfree packages
      allowUnfree = true;
    };
  };

  # ? - Nix global settings
  # * - "https://search.nixos.org/options?channel=25.11&show=nix"
  nix = {
    # * - "https://search.nixos.org/options?channel=25.11&show=nix.settings"
    settings = {
      # ? - Enable experimental features: flakes and modern nix commands
      experimental-features = [ "nix-command" "flakes" ];
    };
  };

  # ? - System configuration settings
  # * - "https://search.nixos.org/options?channel=unstable&show=system"
  system = {
    # ? - NixOS release version for state compatibility
    # * - "https://search.nixos.org/options?channel=unstable&show=system.stateVersion"
    stateVersion = "25.11";
  };
}
